name: Android production build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps-template/**'

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production
