name: iOS production build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps-template/**'

jobs:
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production
